---
- hosts: all
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Creating a repository file for Kubernetes
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Adding repository details in Kubernetes repo file.
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  
  - name: creating a docker repository
    yum_repository:
         description: repo for docker
         name: docker-ce
         baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
         gpgcheck: no

  - name: installing docker
    package:
         name: docker-ce
         state: present
     
  - name: Installing  firewalld
    become_user: root
    shell: |
     yum install firewalld vim wget git bind-utils -y

  - name: starting docker services
    service:
          name: docker
          state: started
  - name: disable SELinux
    command: setenforce 0
  
  - name: disable SELinux on reboot
    selinux:
      state: disabled
 
  - name: Installing required packages
    yum:
     name: "{{ packages }}"
     state: present

  - name: Starting and Enabling the required services
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    with_items: "{{ services }}"

  - name: Allow Network Ports in Firewalld
    firewalld:
     port: "{{ item }}"
     state: enabled
     permanent: yes
     immediate: yes
    with_items: "{{ master_ports }}"

  - name: Enabling Bridge Firewall Rule
    shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"
