
#- name: Kafka download file with check (sha256)
#  get_url:
#    url: https://downloads.apache.org/kafka/2.7.0/kafka-2.7.0-src.tgz
#    dest: /opt/net
#    checksum: sha256:3e4ccc8c1ea85b811b4bc017a599f15df0f13e9639c03c7b8d84952d59895efc

- name: Download Java    
  get_url:
    url: "https://download.java.net/java/GA/jdk15.0.2/0d1cfde4252546c6931946de8db48ee2/7/GPL/openjdk-15.0.2_linux-x64_bin.tar.gz"
    dest: /opt

- name: Unpack Java archive 
  unarchive:
    src: /opt/openjdk-15.0.2_linux-x64_bin.tar.gz
    dest: /opt/
    copy: no
    group: root
    owner: root

- name: Install Java for system
  command: 'alternatives --install "/usr/bin/java" "java" "/opt/jdk-15.0.2/bin/java" 2000'

- name: Clean up Java Downloaded Package 
  file: "state=absent path=/opt/openjdk-15.0.2_linux-x64_bin.tar.gz"
