IMAGE_NAME = "centos/7"
Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.ssh.insert_key = false
    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end

    config.vm.define "app" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "public_network", ip: "192.168.1.250"
        master.vm.hostname = "app"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "app.yml"
            ansible.extra_vars = {
                node_ip: "192.168.1.250",
            }
        end
   end
end 

